# Generated by Django 5.0.3 on 2024-04-01 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_quill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='quill',
        ),
    ]
