# Generated by Django 5.0.3 on 2024-04-01 16:02

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0002_rename_recipi_description_recipe_recipe_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipies',
            name='content',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
