# Generated by Django 5.0.3 on 2024-04-02 07:40

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0004_like_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipies',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
