# Generated by Django 5.0.3 on 2024-04-02 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0006_alter_recipies_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_images',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='recipies.recipies'),
        ),
    ]
