# Generated by Django 5.0.3 on 2024-04-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0008_recipies_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipies',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
