# Generated by Django 5.0.3 on 2024-04-01 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='recipi',
            new_name='recipe',
        ),
        migrations.CreateModel(
            name='Recipe_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Recipe_other_images')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipies.recipies')),
            ],
            options={
                'verbose_name_plural': 'Recipe Images',
            },
        ),
    ]
